title: Reni Rianti Prastiti # your name (or website title) here
logo: "profil_pict.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 A third year accounting student who is willing to learn new things and highly motivated person.
  <br><br>
  Familiar with Microsoft office (word, excel, and PPT), interested in financial issues, financial systems, and marketing strategies analysis on various platforms. Have the ability to work individually and in a team either as a leader or a member.
  <br><br>
  <a href="https://www.linkedin.com/in/reniriantiprastiti/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
